name: comind
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  # firebase_auth: ^4.15.3
  # firebase_core: ^2.24.2
  # firebase_ui_auth: ^1.11.0
  email_validator: ^2.1.17
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.6.0+1
  flutter_quill: ^8.1.1
  google_fonts: ^6.1.0
  http: ^1.1.2
  intl: ^0.18.1
  # markdown: ^7.1.1
  provider: ^6.1.1
  shelf: ^1.4.1
  uuid: ^4.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - fonts/

  fonts:
    - family: "Bungee Pop"
      fonts:
        - asset: fonts/BungeePop.ttf
    - family: "Bungee"
      fonts:
        - asset: fonts/Bungee-Regular.ttf
