// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyAdDYBwPIxYSGGUromvGt7L6r0c3dDrr3M',
//     appId: '1:940891714510:web:5a1b38bfaa4a1293e8319f',
//     messagingSenderId: '940891714510',
//     projectId: 'comind-f863a',
//     authDomain: 'comind-f863a.firebaseapp.com',
//     storageBucket: 'comind-f863a.appspot.com',
//     measurementId: 'G-8LJSP5HVHQ',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyChblXfC5uANpdd7T24DZTX0r4IAlUqhZI',
//     appId: '1:940891714510:android:9aa333eb5e1a2ac3e8319f',
//     messagingSenderId: '940891714510',
//     projectId: 'comind-f863a',
//     storageBucket: 'comind-f863a.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyD-LMFPb0IqcfX7R8xdrSnDY8MmumTG36A',
//     appId: '1:940891714510:ios:617ed912145b2193e8319f',
//     messagingSenderId: '940891714510',
//     projectId: 'comind-f863a',
//     storageBucket: 'comind-f863a.appspot.com',
//     iosBundleId: 'com.example.comind',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyD-LMFPb0IqcfX7R8xdrSnDY8MmumTG36A',
//     appId: '1:940891714510:ios:c669d406afa7944ee8319f',
//     messagingSenderId: '940891714510',
//     projectId: 'comind-f863a',
//     storageBucket: 'comind-f863a.appspot.com',
//     iosBundleId: 'com.example.comind.RunnerTests',
//   );
// }
