name: Deploy to web
on:
  # Enable manual run
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy web build"
        required: true
        default: "staging"
        type: choice
        options:
          - staging
          - prod

# Declare default permissions as read only.
permissions: read-all

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Set up Flutter.
      - name: Clone Flutter repository with master channel
        uses: subosito/flutter-action@cc97e1648fff6ca5cc647fa67f47e70f7895510b
        with:
          channel: master
      - run: flutter doctor -v

      # Checkout gallery code and get packages.
      - name: Checkout gallery code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - run: flutter pub get

      # Build and deploy (by default, to staging).
      - run: flutter build -v web --release --web-renderer html

      - name: Save build results to 'web' branch
        run: |
          git config --global user.name "Cameron Pfiffer"
          git config --global user.email "cameron@pfiffer.org"
          git checkout -b web
          git add build/web/ # Make sure the path is correct
          git commit -m "Add web build results"
          git push --set-upstream origin web
